locals {
  categories = {
    "Accounting & Finance"            = 12
    "Analytics & Reporting"           = 11
    "Architecture & Design"           = 10
    "Automation & Orchestration"      = 13
    "Business Continuity"             = 19
    "Cloud Infrastructure"            = 4
    "Compliance & Audit"              = 16
    "Communication & Collaboration"   = 8
    "Cybersecurity"                   = 1
    "Data Management"                 = 6
    "DevOps & CI/CD"                  = 5
    "Disaster Recovery"               = 18
    "Governance & Risk"               = 15
    "Hardware & Devices"              = 14
    "Human Resources"                 = 20
    "Identity & Access Management"    = 2
    "Networking & Connectivity"       = 3
    "Software Development"            = 7
    "Storage & Backup"                = 9
    "User Support & Operations"       = 17
    "AI & Machine Learning"           = 6
    "Application Management"          = 8
    "Asset Management"                = 13
    "Billing & Payments"              = 12
    "Brand & Marketing"               = 19
    "Change Management"               = 14
    "Client Relationship Management"  = 10
    "Content Management"              = 11
    "Customer Experience"             = 9
    "Customer Support"                = 7
    "Data Analytics"                  = 5
    "Data Privacy"                    = 2
    "Data Warehousing"                = 4
    "Digital Experience"              = 8
    "Digital Transformation"          = 10
    "E-Commerce"                      = 17
    "Engineering & R&D"               = 6
    "Enterprise Applications"         = 11
    "Environmental Sustainability"    = 18
    "Field Operations"                = 16
    "Financial Operations"            = 13
    "Infrastructure Operations"       = 5
    "Integration Services"            = 9
    "Internal Tools"                  = 7
    "IT Governance"                   = 15
    "IT Operations"                   = 4
    "Knowledge Management"            = 8
    "Legal & Compliance"              = 16
    "Licensing & Entitlements"        = 11
    "Logistics & Supply Chain"        = 14
    "Monitoring & Observability"      = 3
    "Performance Optimization"        = 9
    "Platform Engineering"            = 5
    "Procurement & Vendor Management" = 12
    "Product Management"              = 10
    "Project Management"              = 13
    "Quality Assurance & Testing"     = 9
    "Release Management"              = 7
    "Remote Work & Collaboration"     = 8
    "Reporting & Insights"            = 10
    "Research & Innovation"           = 11
    "Resource Planning"               = 12
    "Sales Operations"                = 13
    "Security Operations"             = 1
    "Server Management"               = 4
    "Service Management"              = 6
    "Site Reliability Engineering"    = 3
    "Strategic Planning"              = 15
    "Talent Acquisition"              = 18
    "Technical Support"               = 8
    "Training & Development"          = 9
    "User Experience & Design"        = 10
    "Vendor Management"               = 13
    "Workplace Technology"            = 7
    "Workflow Automation"             = 6
  }
}

resource "jamfpro_category" "categories" {
  for_each = local.categories
  name     = "${var.team-prefix}-${each.key}"
  priority = each.value

}